plugins {
    id 'com.android.application'
}
android {
    namespace 'com.v7.quantumfast'
    compileSdk 34
    defaultConfig {
        applicationId "com.v7.quantumfast"
        minSdk 26
        targetSdk 34
        versionCode 15
        versionName "15.39-STAGE3"
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    buildTypes {
        release {
            minifyEnabled false
        }
        debug {
            minifyEnabled false
        }
    }
}
dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.recyclerview:recyclerview:1.3.2'
}
