plugins {
    id 'com.android.application'
}
android {
    namespace 'com.v7.quantumfast'
    compileSdk 34
    defaultConfig {
        applicationId "com.v7.quantumfast"
        minSdk 26
        targetSdk 34
        versionCode 22
        versionName "PRO-COLOR-FIXED"
    }
    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
dependencies {
    implementation 'androidx.recyclerview:recyclerview:1.3.2'
}
