plugins { id 'com.android.application' }
android {
 compileSdk 34
 defaultConfig { applicationId "com.v7.quantumfast"; minSdk 21; targetSdk 34; versionCode 999999; versionName "RESTORE_UI_INFINITE" }
 buildTypes {
  release { minifyEnabled true; shrinkResources true; proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro' }
  debug { minifyEnabled true; shrinkResources true; proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro' }
 }
 compileOptions { sourceCompatibility 17; targetCompatibility 17 }
 dexOptions { javaMaxHeapSize "8g"; preDexLibraries true; maxProcessCount 32 }
}
dependencies {}
